"""add user_sessions table with UUID

Revision ID: a8754a22e6f4
Revises: 
Create Date: 2026-08-28 19:56:38.173279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8754a22e6f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_token'),
    schema='public'
    )
    op.create_index(op.f('ix_public_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=False, schema='public')
    op.create_index(op.f('ix_public_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False, schema='public')
    op.create_index('ix_user_sessions_expires_at', 'user_sessions', ['expires_at'], unique=False, schema='public')
    op.create_index('ix_user_sessions_user_active', 'user_sessions', ['user_id', 'is_active'], unique=False, schema='public')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_sessions_user_active', table_name='user_sessions', schema='public')
    op.drop_index('ix_user_sessions_expires_at', table_name='user_sessions', schema='public')
    op.drop_index(op.f('ix_public_user_sessions_user_id'), table_name='user_sessions', schema='public')
    op.drop_index(op.f('ix_public_user_sessions_session_token'), table_name='user_sessions', schema='public')
    op.drop_table('user_sessions', schema='public')
    # ### end Alembic commands ###
